### ISSUE TITLE
Closes as I open it

### ISSUE THREAD

**Issue by Blodgharm97** [pgaskin/kepubify#54]
Hi! The program closes three secons after I open it, I can't do anything, even executing as admin there's no change. Anyone knows how to fix it?

**Comment by pgaskin** [comment]
Kepubify is a command-line application. You can use it from Command Prompt or PowerShell. Alternatively, if you only need to convert files/folders without any additional options you can just drag and drop them onto the executable.

**Comment by Blodgharm97** [comment]
Wow that's brilliant! Thanks so much!
