### ISSUE TITLE
application/xhtml+xml files with .xml extension are not converted

### ISSUE THREAD

**Issue by fthdgn** [pgaskin/kepubify#55]
Public domain books from Feedbooks use .xml extension for "application/xhtml+xml" files. Kepubify does not add "kobospan" classes to html files with extension .xml.

Is it possible to support these type epub files?

Some of the books I tried:
http://www.feedbooks.com/book/92.epub
http://www.feedbooks.com/book/52.epub
http://www.feedbooks.com/book/81.epub

**Comment by pgaskin** [comment]
I'll look into this. I'll probably need to rework the scanning logic to add xml files specified as `application/xhtml+xml` in the OPF. Alternatively, I could test all XML files and detect if they're XHTML.
