### ISSUE TITLE
Documentation: important to note that in-place Calibre conversion doesn't update Calibre database

### ISSUE THREAD

**Issue by cristoslc** [pgaskin/kepubify#60]
On https://pgaskin.net/kepubify/, there's an example labeled  `To convert a calibre library in-place:`. Performing this command (with no additional action) will create "orphaned" kepub files that are not recognized in the Calibre database.

It would be helpful to include a warning alongside this example, so that Calibre users understand that the process is not entirely handled by kepubify.  Such users can use the [`calibredb add`](https://manual.calibre-ebook.com/generated/en/calibredb.html#add) terminal command to add the relevant files to the database using `calibredb add -m 'ignore' <<FILE.kepub>>`.

For instance, in Windows, you can use PowerShell to add all of the converted kepubs with the following command. It may take  a long time, depending on the size of your database.
```
dir -Path 'DRIVE:\Path\To\Calibre Library\' -Filter *.kepub -Recurse | %{calibredb add -m 'ignore' $_.FullName}
```
A similar (untested) command for bash on macOS/Linux would be:
```
find /path/to/Calibre\ Library/ \( -name '*.kepub' \) -print0 | xargs -0 calibredb add -m 'ignore' 
```

If you wanted to make this process slightly easier for Calibre users, you could modify the `--calibre` flag so that it outputs an appropriate batch file automatically, which just uses this pattern for each line:
```
calibredb add -m 'ignore' "<<convertedFile.kepub>>"
```

Users could then simply execute that batch file on completion and only the converted files would be added to their Calibre database. (Users with more than one library would need to make modifications, but are more likely to have the skills to modify the commands appropriately.)

**Comment by pgaskin** [comment]
Thanks for this advice! The macOS/Linux one looks correct.

I'll probably add an option to write a list of converted files to a user-specified file, since that would be useful in general, and would fit with the overall goal of kepubify (whereas generating a script would be out of scope).

I'm not a calibre user myself, so I have a few questions. What happens if there is already a kepub in the database? Also, will any common user settings cause this to fail or break something?

**Comment by cristoslc** [comment]
> *What happens if there is already a kepub in the database?*

The `-m 'ignore'` flag tells it to merge only if there's no KEPUB file already in the database. If there is an existing KEPUB, it skips that record entirely. There are also flags to overwrite existing KEPUBs or to add new book entries when there's a conflict with an existing file. (Docs at https://manual.calibre-ebook.com/generated/en/calibredb.html#add)

> *Also, will any common user settings cause this to fail or break something?*

This `calibredb` call doesn't specify which Calibre library to target, so users with multiple libraries could wind up adding the files to the wrong library. Also, while I didn't seem to have issues with the merge finding the right matching ebooks (I assume that's because metadata was copied from the epubs?), it's obviously not well-tested in a variety of library environments, so 🤷🏽‍♂️.

> *I'll probably add an option to write a list of converted files to a user-specified file, since that would be useful in general, and would fit with the overall goal of kepubify (whereas generating a script would be out of scope).*

I definitely see value in having a separate flag that outputs a list of the converted files (with full paths). I'm a little unclear on where you see the scope beginning/ending, given that your flag is explicitly called `--calibre`? Would it make sense to change that flag to something less loaded, like `--extkepub`?

Really appreciate the work you put into this utility -- thanks for all your efforts!

**Comment by pgaskin** [comment]
One last question: Does calibre expect the converted file to be up to date with the external metadata file? What happens if the metadata doesn't match?

> extkepub

Well, Calibre is the only one which uses this so there's not much point in pretending it isn't, and I'd rather not support arbitrary extensions if I can help it. Also, it's the only single-word extension I can imagine would be used for kepubs.

**Comment by cristoslc** [comment]
> *One last question: Does calibre expect the converted file to be up to date with the external metadata file? What happens if the metadata doesn't match?*

Good question. If the metadata in the converted KEPUB doesn't match the metadata in the Calibre DB, then they'll get imported as new books (because they won't match correctly with existing ones). You can fix this by running an "Embed Metadata" on your Calibre library first.  

It turns out I did have a handful of books that exhibited this problem because the embedded metadata didn't match the hand-modified Calibre metadata.

> *Well, Calibre is the only one which uses this so there's not much point in pretending it isn't, and I'd rather not support arbitrary extensions if I can help it. Also, it's the only single-word extension I can imagine would be used for kepubs.*

Just to make sure I was being clear, I wasn't suggesting that kepubify should support arbitrary extensions, just that `--calibre` as a flag could imply a level of integration that you don't intend. But obviously it's your decision to make.
