### ISSUE TITLE
Incorrect documentation on for `Converting your Calibre library with kepubify (Linux/macOS)`

### ISSUE THREAD

**Issue by Rudo2204** [pgaskin/kepubify#69]
https://pgaskin.net/kepubify/docs/
At step 3 I think we need to add `--calibre` flag and at step 4 we will need to use: `find "$LIBRARY" -name '*.kepub' | xargs -I _ calibredb add -m 'ignore' _ ` to deal with directories/files that have space or other unwanted stuff in it.

**Comment by Rudo2204** [comment]
Also at step 3 I think `library` should be all capitalized

**Comment by pgaskin** [comment]
Oops, looks like I made a typo when writing that part. I'll fix that soon.

**Comment by pgaskin** [comment]
Fixed; sorry about the delay.
