### ISSUE TITLE
Converted Epub not loading on Kobo Aura Edition 2

### ISSUE THREAD

**Issue by Arathonk** [pgaskin/kepubify#71]
I've tried loading an epub file, and it did without problems,
Then I tried converting it to kepub, but it won't open the file then on my Kobo Aura Edition 2, what could be the problem?

**Comment by pgaskin** [comment]
Doe the book import correctly?

**Comment by pgaskin** [comment]
No, as in does it show up in the library on the device?

**Comment by Arathonk** [comment]
No it can't load it..

**Comment by pgaskin** [comment]
You'll need to send me the book so I can have a look.

**Comment by pgaskin** [comment]
I haven't received the EPUB file, so I'm going to close this issue for now. Feel free to re-open it with more details.
