### ISSUE TITLE
Seriesmeta CGO_ENABLED=0

### ISSUE THREAD

**Issue by Kuchenm0nster** [pgaskin/kepubify#75]
Hi I tried to use seriesmeta linux-arm, linux-amd64 and win-amd64 but since cgo is not enabled go-sqlite3 won't work.
How am I supposed to use seriesmeta because I always get the following error:

```
Note: You might be interested in NickelSeries (https://go.pgaskin.net/kobo/ns), which will automatically import series and subtitle metadata along with the book itself.
Finding kobo
Opening kobo
Could not open Kobo eReader: could not open KoboReader.sqlite: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub.
```

**Comment by pgaskin** [comment]
Oops... copy-paste error while making the GH actions config. I'll fix that soon.

But, note that the recommend solution for series metadata is now my [NickelSeries](https://pgaskin.net/kepubify/ns) mod, which integrates seamlessly with the import process.

**Comment by Kuchenm0nster** [comment]
Good to know, I've read about it but did not use it because of your note:

> Note: I recommend using my new mod, NickelSeries, after you run seriesmeta once. 

I thought you need to run seriesmeta onve for some changes on the kobo sqlite file but since seriesmeta did not run I did not try Nickelseries.

**Comment by pgaskin** [comment]
I'll reword that too to make it more clear that you only need to run seriesmeta if you want to import the metadata of existing books.

**Comment by Kuchenm0nster** [comment]
thanks. I tried NickelSeries and it works like a charm. Thanks for this awesome little tool. Weird Kobo does not support this natively
