### ISSUE TITLE
Kepubify Mac does not work

### ISSUE THREAD

**Issue by Paramstr** [pgaskin/kepubify#85]
Does not generate any converted files in the root directory. Terminal Output has this;
10 total: 10 converted, 0 copied, 0 skipped, 0 errored

However no books are seen any the directory.

**Comment by pgaskin** [comment]
Have you checked both the directory containing the books you are converting and the current directory in the terminal?

**Comment by Paramstr** [comment]
Hey thanks for the speedy reply. Yea it turns out the terminal wasn't open in the directory I wanted it to be so I wasn't seeing the files. But have found the converted books now.

**Comment by pgaskin** [comment]
See [here](https://github.com/pgaskin/kepubify/runs/6540738879?check_suite_focus=true#step:7:8) for some additional examples.
