### ISSUE TITLE
What tag/class does kepubify need to recognize an endnote?

### ISSUE THREAD

**Issue by jeff47** [pgaskin/kepubify#96]
I'm very puzzled trying to add endnotes to a book I am converting from a PDF.  I tried using `<aside>` and also `<a>`, but I get complete jumps instead of the popups.  What does kepubify look for when converting a footnote?

**Comment by pgaskin** [comment]
It's not kepubify which determines if something is a footnote. See [here](https://github.com/kobolabs/epub-spec#footnotesendnotes-are-fully-supported-across-kobo-platforms) for more information on how Kobo detects them.

**Comment by jeff47** [comment]
Oh, thank you!  I misunderstood the description on kepubify's main page -- I thought it was applying some formatting.
